version: '3'

# x-common-variables: &common-variables
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: password

volumes:
  mysql_sandbox_data:
  mysql_development_data:
  server_node_modules:
  client_node_modules:

services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: nfs
    ports:
      - $DATABASE_PORT:3306
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u$$DATABASE_USER',
          '-p$$DATABASE_PASSWORD',
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - 'mysql_${PLAID_ENV}_data:/var/lib/mysql'

  api:
    container_name: api
    image: need-for-spend:server-debug-${APP_VERSION}
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
      target: debug
    restart: always
    ports:
      - $SERVER_PORT:8080
    environment:
      APP_VERSION:
      PLAID_CLIENT_ID:
      PLAID_SECRET:
      PLAID_ENV:
      PLAID_PRODUCTS:
      PLAID_COUNTRY_CODES:
      PLAID_REDIRECT_URI:
      # APP Configuration
      SERVER_PORT:
      ADMIN_PASSWORD:
      # DATABASE
      DATABASE_USER:
      DATABASE_PASSWORD:
      DATABASE_PORT:
      DATABASE_HOST:
      DATABASE_NAME:
      # JWT
      JWT_SECRET:
      DATABASE_URL: 'mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./packages/server:/app/packages/server
      - server_node_modules:/app/node_modules

  web:
    container_name: web
    image: need-for-speed:web-debug-${APP_VERSION}
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
      target: debug

      # Next.js requires the following environment variables to be set at build time
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
    environment:
      APP_VERSION:
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./packages/client:/app/packages/client
      - client_node_modules:/app/node_modules

    # networks:
    #   - app_network
    # Define a network, which allows containers to communicate
    # with each other, by using their container name as a hostname
    # networks:
    #   app_network:
    #     external: true
