import { DailySumOverTime } from '../transactions'

export const fakeDaily: DailySumOverTime[] = [
  {
    year: 2023,
    month: 6,
    day: 12,
    expense: 6.33,
    income: 0,
    count: '1',
  },
  {
    year: 2023,
    month: 5,
    day: 30,
    expense: 5.4,
    income: 0,
    count: '1',
  },
  {
    year: 2023,
    month: 5,
    day: 28,
    expense: 0,
    income: 500,
    count: '1',
  },
  {
    year: 2023,
    month: 5,
    day: 27,
    expense: 16.33,
    income: 0,
    count: '2',
  },
  {
    year: 2023,
    month: 5,
    day: 26,
    expense: 89.4,
    income: 0,
    count: '1',
  },
  {
    year: 2023,
    month: 5,
    day: 13,
    expense: 6.33,
    income: 0,
    count: '1',
  },
  {
    year: 2023,
    month: 4,
    day: 30,
    expense: 5.4,
    income: 0,
    count: '1',
  },
  {
    year: 2023,
    month: 4,
    day: 28,
    expense: 0,
    income: 500,
    count: '1',
  },
  {
    year: 2023,
    month: 4,
    day: 27,
    expense: 16.33,
    income: 0,
    count: '2',
  },
  {
    year: 2023,
    month: 4,
    day: 26,
    expense: 89.4,
    income: 0,
    count: '1',
  },
  {
    year: 2023,
    month: 4,
    day: 13,
    expense: 6.33,
    income: 0,
    count: '1',
  },
  {
    year: 2023,
    month: 3,
    day: 31,
    expense: 5.4,
    income: 0,
    count: '1',
  },
  // {
  //   year: 2023,
  //   month: 3,
  //   day: 29,
  //   expense: 0,
  //   income: 500,
  //   count: '1',
  // },
  // {
  //   year: 2023,
  //   month: 3,
  //   day: 28,
  //   expense: 16.33,
  //   income: 0,
  //   count: '2',
  // },
  // {
  //   year: 2023,
  //   month: 3,
  //   day: 27,
  //   expense: 89.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2023,
  //   month: 3,
  //   day: 14,
  //   expense: 6.33,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2023,
  //   month: 3,
  //   day: 1,
  //   expense: 5.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2023,
  //   month: 2,
  //   day: 27,
  //   expense: 0,
  //   income: 500,
  //   count: '1',
  // },
  // {
  //   year: 2023,
  //   month: 2,
  //   day: 26,
  //   expense: 16.33,
  //   income: 0,
  //   count: '2',
  // },
  // {
  //   year: 2023,
  //   month: 2,
  //   day: 25,
  //   expense: 89.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2023,
  //   month: 2,
  //   day: 12,
  //   expense: 6.33,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2023,
  //   month: 1,
  //   day: 30,
  //   expense: 5.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2023,
  //   month: 1,
  //   day: 28,
  //   expense: 0,
  //   income: 500,
  //   count: '1',
  // },
  // {
  //   year: 2023,
  //   month: 1,
  //   day: 27,
  //   expense: 16.33,
  //   income: 0,
  //   count: '2',
  // },
  // {
  //   year: 2023,
  //   month: 1,
  //   day: 26,
  //   expense: 89.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2023,
  //   month: 1,
  //   day: 13,
  //   expense: 6.33,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 12,
  //   day: 31,
  //   expense: 5.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 12,
  //   day: 29,
  //   expense: 0,
  //   income: 500,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 12,
  //   day: 28,
  //   expense: 16.33,
  //   income: 0,
  //   count: '2',
  // },
  // {
  //   year: 2022,
  //   month: 12,
  //   day: 27,
  //   expense: 89.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 12,
  //   day: 14,
  //   expense: 6.33,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 12,
  //   day: 1,
  //   expense: 5.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 11,
  //   day: 29,
  //   expense: 0,
  //   income: 500,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 11,
  //   day: 28,
  //   expense: 16.33,
  //   income: 0,
  //   count: '2',
  // },
  // {
  //   year: 2022,
  //   month: 11,
  //   day: 27,
  //   expense: 89.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 11,
  //   day: 14,
  //   expense: 6.33,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 11,
  //   day: 1,
  //   expense: 5.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 10,
  //   day: 30,
  //   expense: 0,
  //   income: 500,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 10,
  //   day: 29,
  //   expense: 16.33,
  //   income: 0,
  //   count: '2',
  // },
  // {
  //   year: 2022,
  //   month: 10,
  //   day: 28,
  //   expense: 89.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 10,
  //   day: 15,
  //   expense: 6.33,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 10,
  //   day: 2,
  //   expense: 5.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 9,
  //   day: 30,
  //   expense: 0,
  //   income: 500,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 9,
  //   day: 29,
  //   expense: 16.33,
  //   income: 0,
  //   count: '2',
  // },
  // {
  //   year: 2022,
  //   month: 9,
  //   day: 28,
  //   expense: 89.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 9,
  //   day: 15,
  //   expense: 6.33,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 9,
  //   day: 2,
  //   expense: 5.4,
  //   income: 0,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 8,
  //   day: 31,
  //   expense: 0,
  //   income: 500,
  //   count: '1',
  // },
  // {
  //   year: 2022,
  //   month: 8,
  //   day: 30,
  //   expense: 16.33,
  //   income: 0,
  //   count: '2',
  // },
  // {
  //   year: 2022,
  //   month: 8,
  //   day: 29,
  //   expense: 89.4,
  //   income: 0,
  //   count: '1',
  // },
]
