export type ErrorResponse = {
  code: number
  message: string
}

export type Institution = {
  institution_id: string
  name: string
  url?: string | null
  primary_color?: string | null
  /**
   * Base64 encoded representation of the institution\'s logo
   * @type {string}
   * @memberof Institution
   */
  logo?: string | null
}

/** ------- Generated by Prisma ----------- */

/**
 * Model User
 *
 */
export type User = {
  id: string
  email: string
  password: string
  firstName: string
  lastName: string
  role: number
  createdAt: Date
  updatedAt: Date
}

/**
 * Model Item
 *
 */
export type Item = {
  id: string
  plaidAccessToken: string
  plaidItemId: string
  plaidInstitutionId: string
  plaidInstitutionName: string
  transactionsCursor: string | null
  userId: string
  createdAt: Date
  updatedAt: Date
}

/**
 * Model Account
 *
 */
export type Account = {
  id: string
  itemId: string
  plaidAccountId: string
  name: string
  type: string
  subtype: string | null
  mask: string | null
  officialName: string | null
  balanceAvailable: number | null
  balanceCurrent: number | null
  balanceLimit: number | null
  balanceIsoCurrencyCode: string | null
  balanceUnofficialCurrencyCode: string | null
  createdAt: Date
  updatedAt: Date
}

/**
 * Model Transaction
 *
 */
// {
//   "id": "967e2b5a-648a-4cfa-ae7d-2a70e306609c",
//   "plaidTransactionId": "E8MQnPzBGwuKL6PE35koCAdgPaEpXWIg5JL9D",
//   "accountId": "439d2b78-3495-431c-b5f6-0af71af411d1",
//   "date": "2023-06-12",
//   "datetime": null,
//   "address": null,
//   "name": "Uber 072515 SF**POOL**",
//   "amount": 6.33,
//   "isoCurrencyCode": "USD",
//   "unofficialCurrencyCode": null,
//   "plaidCategoryId": "22016000",
//   "pending": false,
//   "accountOwner": null,
//   "createdAt": "2023-06-17T20:32:42.578Z",
//   "updatedAt": "2023-06-17T20:32:44.790Z",
//   "account": {
//     "item": {
//       "userId": "8bc1a0e4-b1b5-49c1-8c16-6637f85c4a64"
//     }
//   },
//   "category": {
//     "name": "Travel",
//     "subcategories": [
//       {
//         "subcategoryName": "Taxi"
//       }
//     ]
//   }
// },

export type Transaction = {
  id: string
  plaidTransactionId: string
  accountId: string
  date: string
  datetime: string | null
  address: string | null
  name: string | null
  amount: number
  isoCurrencyCode: string | null
  unofficialCurrencyCode: string | null
  plaidCategoryId: string | null
  pending: boolean
  accountOwner: string | null
  account: {
    item: {
      userId: string
    }
  }
  createdAt: Date | string
  updatedAt: Date | string
} & {
  category: Pick<Category, 'name' | 'subcategories'>
}

/**
 * Model Category
 *
 */
export type Category = {
  plaidCategoryId: string
  name: string
  subcategories: Pick<Subcategory, 'subcategoryName'>[]
  group: string
  createdAt: Date
  updatedAt: Date
}

/**
 * Model Subcategory
 *
 */
export type Subcategory = {
  subcategoryName: string
  depth: number
  createdAt: Date
  updatedAt: Date
}

/**
 * Model CategoriesOnSubcategories
 *
 */
export type CategoriesOnSubcategories = {
  plaidCategoryId: string
  subcategoryName: string
  createdAt: Date
  updatedAt: Date
}
