name: Test

on:
  push:
    branches: [feature/ci] # TODO: Replace after debugging

jobs:
  test:
    runs-on: self-hosted

    env:
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_PORT: 3306
      # APP Configuration
      SERVER_PORT: 8080
      ADMIN_PASSWORD: admin-test
      # JWT
      JWT_SECRET: jwt-test
      DATABASE_URL: 'mysql://root:root@localhost:8080/finme'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.9.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Tests
        run: yarn test
